26\05\2026

numpy

In [1]:
import numpy as np

In [ ]:
# create a array
a=np.array(['python',45,89,12.6,30.27,True])
a

In [ ]:
a1=np.array([45,89,12.6,30.27])
a1

In [ ]:
a1.shape

In [ ]:
a2=np.array([[10,20],[30,40],[4,3]])
a2

In [ ]:
a2.shape

In [ ]:
# to cheak dimention of data
a2.ndim

In [ ]:
len(a2)

In [ ]:
type(a2)

In [ ]:
a2.dtype

In [ ]:
np.zeros((3,3),dtype='int')

In [ ]:
np.ones((2,3),dtype='int')

In [ ]:
np.full((3,3),8)

In [ ]:
np.identity(3,dtype='int')

In [ ]:
np.eye(3,dtype='int')

In [ ]:
# range function
ar1=np.arange(1,10,1)
ar1

In [ ]:
np.reshape(ar1,(3,3))

In [ ]:
# 1 to 20 even num
ar2=np.arange(2,21,2)
ar2

In [ ]:
# 1 to 20 odd num
ar3=np.arange(1,21,2)
ar3

In [ ]:
ar4=np.random.rand(4,5).round(2)
ar4

In [4]:
ar5=np.random.randint(1,100,(4,5))
ar5

array([[14, 56, 77, 60, 54],
       [ 3, 82, 39, 74, 42],
       [59,  5, 64, 53, 26],
       [47, 91, 76, 70, 52]], dtype=int32)

In [6]:
np.max(ar5)

np.int32(91)

In [ ]:
ar5.min()

In [9]:
# create a np array of 3x4 with number from  10 to 50
ar6=np.random.randint(10,50,(3,4))
ar6

array([[40, 13, 37, 17],
       [41, 21, 28, 31],
       [22, 49, 37, 31]], dtype=int32)

In [11]:
np.max(ar6)

np.int32(49)

In [12]:
np.linspace(10,50,12).round(2)

array([10.  , 13.64, 17.27, 20.91, 24.55, 28.18, 31.82, 35.45, 39.09,
       42.73, 46.36, 50.  ])

In [13]:
# analys row wise max value 
row_max=ar6.max(axis=1)
row_max

array([40, 41, 49], dtype=int32)

In [ ]:
# analyse the position of the max value and it is show that 1st-8
np.argmax(arri,axis=1)

In [ ]:
arr1[1,2]

In [ ]:
arr1[0]

In [ ]:
arr1[10]

In [ ]:
arr1

In [ ]:
arr1[2,2] = 44

In [ ]:
arr1[2,2]

In [ ]:
arr1[1,1] = 27

In [ ]:
arr1[1,1:3)

In [ ]:
arr1[::2,1::2]

In [ ]:
arr1.transpose()

In [ ]:
#reverse bath(col, rows)
arr1:-1:-11

In [ ]:
# normalize the value in blw range and 1
#x-min/max-min
new (arr1 arr1.min())/(arr1.max() arri.min())
new

In [ ]:
nем.round(2)

In [ ]:
arr1

In [ ]:
# how to analyse 138 values
arr1[arr1>30]

In [ ]:
# how to analyse 138 values
arr1[arr1>30]

In [ ]:
arr2= np.array(123,-56,39,-18,-12,45,-153) arr2

In [ ]:
arr240